logging:
  receivers:
    my-webapp-receiver:
      type: files
      include_paths:
        - /var/log/webapp/application.log
      record_log_file_path: true
  processors:
    my-webapp-processor:
      type: parse_json
      time_key: timestamp
      time_format: '%Y-%m-%dT%H:%M:%S.%L%z'
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      default_pipeline:
        receivers: [my-webapp-receiver]
        processors: [my-webapp-processor, move_severity]"