name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "Godofwar@321"
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
      # set a new variable to the current date
      - name: Set sequalize environment
        run: export NODE_ENV=development
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.4
      
      - name: Build application artifact
        run: zip -r webapp.zip ./
      
      - name: Install dependencies
        run: npm ci
      # - run: npm run build --if-present

      - name: Start Server
        run: npm run start &

      - name: Run Test
        run: npm run test2

      # Authenticate with GCP using service account key
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Build image
        run: |
          packer init -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "zone=${{ secrets.ZONE }}" packer
          packer build -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "zone=${{ secrets.ZONE }}" packer
